import Head from "next/head";
import Image from "next/image";
import { useRef, useEffect } from "react";
import { gsap } from "gsap";
import ScrollTrigger from "gsap/dist/ScrollTrigger";
import { NavBarOverlay } from "../modules/overlay";
gsap.registerPlugin(ScrollTrigger);
export default function Home() {
  const opacityText = useRef();

  return (
    <>
      <Head>
        <title>home page </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBarOverlay />
    </>
  );
}
